version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: musicdownload:1.1.4
    container_name: musicDownload
    restart: always
    ports:
      - 5500:5000
    volumes:
      - /vol1/1000/wyy_music:/app/downloads
    networks:
      - my_network
    environment:
      - EVN=production
      - DATABASE_URL=mysql+pymysql://root:Zxc1470.@100.77.166.55/music_download
networks:
  my_network:
    external: true