version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: leechee_ii/musicdownload:1.1.7
    container_name: musicDownload
    restart: always
    ports:
      - 5500:5000
    volumes:
      - /vol1/1000/wyy_music:/app/downloads
    environment:
      - EVN=production
      - DATABASE_URL=mysql+pymysql://root:Zxc1470.@100.77.166.55/music_download